// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/security/v1alpha1.PodSecurityPolicyBinding":       schema_pkg_apis_security_v1alpha1_PodSecurityPolicyBinding(ref),
		"./pkg/apis/security/v1alpha1.PodSecurityPolicyBindingSpec":   schema_pkg_apis_security_v1alpha1_PodSecurityPolicyBindingSpec(ref),
		"./pkg/apis/security/v1alpha1.PodSecurityPolicyBindingStatus": schema_pkg_apis_security_v1alpha1_PodSecurityPolicyBindingStatus(ref),
	}
}

func schema_pkg_apis_security_v1alpha1_PodSecurityPolicyBinding(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PodSecurityPolicyBinding is the Schema for the podsecuritypolicybindings API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/security/v1alpha1.PodSecurityPolicyBindingSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/security/v1alpha1.PodSecurityPolicyBindingStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/security/v1alpha1.PodSecurityPolicyBindingSpec", "./pkg/apis/security/v1alpha1.PodSecurityPolicyBindingStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_security_v1alpha1_PodSecurityPolicyBindingSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PodSecurityPolicyBindingSpec defines the desired state of PodSecurityPolicyBinding",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_security_v1alpha1_PodSecurityPolicyBindingStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PodSecurityPolicyBindingStatus defines the observed state of PodSecurityPolicyBinding",
				Type:        []string{"object"},
			},
		},
	}
}
