apiVersion: security.cloudfoundry.org/v1alpha1
kind: PodSecurityPolicyBinding
metadata:
  name: test1
spec:
  policy: unprivileged
  subjects:
  - kind: ServiceAccount
    namespace: psp
    name: default
