kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: security-operator
subjects:
- kind: ServiceAccount
  name: security-operator
  namespace: psp
roleRef:
  kind: ClusterRole
  name: security-operator
  apiGroup: rbac.authorization.k8s.io
