apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: security-operator
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - '*'
