---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer

---
# Allow the deployer to create pods
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployer-editor
subjects:
- kind: ServiceAccount
  # TODO: Change this namespace to the namespace you use for the deployer
  namespace: foo
  name: deployer
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
